apiVersion: devops.kubesphere.io/v1alpha1
kind: S2iRun
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: tomcat-s2irun
  namespace: default
spec:
  builderName: s2ibuilder-b2i-tomcat
  newTag: v0.1.0

