apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: tomcat-s2i
    s2ibuilder-b2i-tomcat: s2ibuilder-b2i-tomcat
  name: tomcat-s2i
  namespace: default
spec:
  podManagementPolicy: OrderedReady
  replicas: 0
  revisionHistoryLimit: 10
  serviceName: test
  selector:
    matchLabels:
      app: tomcat-s2i
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: tomcat-s2i
    spec:
      containers:
        - image: runzexia/hello-java:latest
          imagePullPolicy: Always
          name: container-frx25k
          resources:
            limits:
              cpu: 100m
              memory: 200Mi
            requests:
              cpu: 10m
              memory: 10Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: default
      serviceAccountName: default
      terminationGracePeriodSeconds: 30
  updateStrategy:
    rollingUpdate:
      partition: 0
    type: RollingUpdate
