kind: Deployment
apiVersion: apps/v1
metadata:
  name: python-s2i
  namespace: test
  labels:
    app: python-s2i
  annotations:
    creator: admin
    deployment.kubernetes.io/revision: '1'
    desc: ''
    displayName: ''
    kubesphere.io/isElasticReplicas: 'false'
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-s2i
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: python-s2i
    spec:
      containers:
        - name: python
          image: 'runzexia/hello-python:v0.0.1'
          ports:
            - containerPort: 8080
              protocol: TCP
          resources:
            limits:
              cpu: 100m
              memory: 200Mi
            requests:
              cpu: 10m
              memory: 10Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      serviceAccountName: default
      serviceAccount: default
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
