apiVersion: devops.kubesphere.io/v1alpha1
kind: S2iBuilderTemplate
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: s2ibuildertemplate-python
  spec:
    baseImages:
      - kubespheredev/python-35-centos7
      - kubespheredev/python-34-centos7
    codeFramework: python
    defaultBaseImage: kubespheredev/python-34-centos7
    version: 0.0.1
