name: Image Build

on:
  push:
    branches:
      - master
      - test-* # make it be easier for contributors to test
    tags:
      - 'v*.*.*'

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Docker meta for KubeSphere
      id: meta
      uses: docker/metadata-action@v3
      with:
        images: |
          kubesphere/s2ioperator
        tags: |
          type=schedule
          type=ref,event=branch
          type=ref,event=pr
          type=semver,pattern=v{{version}}
          type=semver,pattern=v{{major}}.{{minor}}
          type=semver,pattern=v{{major}}
          type=sha
    - name: Build env
      id: build_env
      run: |
        if [ ${{ github.ref_type }} == "tag" ]
        then
            echo "::set-output name=platforms::linux/amd64,linux/arm64"
        else
            echo "::set-output name=platforms::linux/amd64"
        fi
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USER }}
        password: ${{ secrets.DOCKER_HUB_SECRETS }}
    - name: Build and push Docker images
      uses: docker/build-push-action@v2.4.0
      with:
        context: .
        file: deploy/Dockerfile
        tags: ${{ steps.meta.outputs.tags }}
        push: true
        labels: ${{ steps.meta.outputs.labels }}
        platforms: ${{ steps.build_env.outputs.platforms }}
